ag - added current milk price to user frontend
ucsb-cs156-s23/proj-happycows-s23-6pm-1 pull request #29
Opened 2023-05-30 21:24 UTC by awgranados

In this PR, we tweaked the front end to display the current milk price of the commons that the user is currently in.

2023-05-30 22:30 UTC, mfletcher2 submitted a review, later dismissed
On second thought, this does not LGTM.

2023-05-30 23:09 UTC, pconrad commented
@AlexanderRobles-CS Please see https://ucsb-cs156-s23.slack.com/archives/C050779M19P/p1685400785702049

and then add a screenshot and link to the before and after for the storybook for this component.

2023-05-31 06:44 UTC, pconrad requested changes
Since this is a frontend changes, it needs a storybook link... and currently, the storybook is out of sync with this component.

When it was originally written, it took only a userCommons property, but now it takes a commons property as well. The storybook was never updated to match, so when you look at your change in the storybook, no milk price shows up.

Fortunately, it's an easy fix... see below.

2023-05-31 06:44 UTC, pconrad commented on frontend/src/main/components/Commons/ManageCows.js
> +            <Card.Title>Current Milk Price: ${commons?.milkPrice}</Card.Title>
It would be helpful to modify the storybook entry so that we can see the milk price there.

It isn't showing up right now:

https://ucsb-cs156-s23.github.io/proj-happycows-s23-6pm-1/prs/29/storybook/?path=/story/components-commons-managecows--uncontrolled

2023-05-31 06:44 UTC, pconrad commented on frontend/src/main/components/Commons/ManageCows.js
> +            <Card.Title>Current Milk Price: ${commons?.milkPrice}</Card.Title>
I think in this code inside this part of `frontend/src/stories/components/Commons/ManageCows.stories.mdx` needs to change to pass in a fixture for commons as well; then your update to the milk price will show up in the storybook.

```
<Canvas>
  <Story name="uncontrolled">
    <ManageCows userCommons = {userCommonsFixtures.oneUserCommons[0]} onBuy={(userCommons) => { console.log("onBuy called:",userCommons); }} onSell={ (userCommons) => { console.log("onSell called:",userCommons); }} />
  </Story>
</Canvas>
```

2023-06-06 01:44 UTC, mfletcher2 approved these changes
LGTM

2023-06-06 16:01 UTC, pconrad approved these changes
LGTM

2023-06-06 16:01 UTC, merged