Fix profit table overflow
ucsb-cs156-s23/proj-happycows-s23-6pm-1 pull request #31
Opened 2023-05-30 22:25 UTC by awgranados

In this PR, we changed the table style in order to support horizontal scrolling, and to prevent the table from overflowing.
Before:
<img width="851" alt="Screenshot 2023-05-30 at 3 22 41 PM" src="https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-1/assets/114529890/f9fa7bc8-b536-4d36-9497-278ac1082ce2">
After:
<img width="852" alt="Screenshot 2023-05-30 at 3 22 02 PM" src="https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-1/assets/114529890/765fac37-2825-4cb9-8a56-513eacfdbf80">

2023-05-31 00:15 UTC, TheRealJBomb approved these changes, later dismissed
LGTM. This is a responsive design fix and also adds the current milk price to this page.

2023-05-31 07:26 UTC, pconrad requested changes
At the time of this code review, there were two commits on this branch separating it from main.

We only want one of those in this PR.

I left a long thread on slack explaining how to cherry pick a branch that has only one of the two commits, and in the process, I made that branch.  It's called `alex-fix-profits-table-v2`

You could do a new PR from that branch.  Or you could use the git reset  and git push -f commands to make the `alex-fix-profits-table` branch (i.e. this PR) point to where the branch `alex-fix-profits-table-v2` points now.  That's how the cool kids do it.

2023-05-31 07:26 UTC, pconrad commented on frontend/src/main/components/Commons/ManageCows.js
>                          <Card.Text>
This is someone else's PR, right?

That one is blocked waiting on a response to a code review issue, so I can't merge this with this included.

I tested the other change, and it works, so I was ready to merge this until I saw the unrelated changes in ManageCows.js.   

If you can remove that change from this branch, this is mergeable for 5 points.

2023-06-03 23:59 UTC, awgranados commented
I've removed the edits to ManageCows.js, and there are now only edits that are relevant to the table overflow bug left on this PR.

2023-06-04 01:46 UTC, mfletcher2 reviewed
You need to include the storybook links in the description https://ucsb-cs156-s23.slack.com/archives/C050779M19P/p1685400785702049

2023-06-04 18:01 UTC, mfletcher2 approved these changes
LGTM

2023-06-04 20:09 UTC, briggsrr approved these changes
LGTM 🚀  

Tested on QA.

2023-06-04 20:12 UTC, merged