Adding Placeholder Instructor Report Button to Job Table
ucsb-cs156-s23/proj-happycows-s23-6pm-1 pull request #50
Opened 2023-06-06 19:41 UTC by albertyu03

In this pr, I added a functional button to the instructor report accordion section of the job table within manage jobs, with a toast message.

# Images #

## Before: ##
<img width="981" alt="image" src="https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-1/assets/92063396/03b61434-0df4-4f45-97e4-b38d3c02627b">

## After: ##
<img width="981" alt="image" src="https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-1/assets/92063396/effb6488-5389-473f-84b1-ac32427fecc4">

<img width="242" alt="image" src="https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-1/assets/92063396/26017c4f-6336-4b2f-9243-59879183541b">

# Storybook #

2023-06-06 21:43 UTC, GlassBricks submitted a review, later dismissed
Looks Good To Me
However, I don't know what the instructor's opinions are on having a frontend component that doesn't yet have backend functionality.

2023-06-08 01:17 UTC, pconrad commented on frontend/src/main/pages/AdminJobsPage.js
> +        toast('Submitted Job: Instructor Report (wip)');
Can we change this to:
```suggestion
        toast('Instructor report not yet implemented; coming soon');
```

2023-06-08 01:18 UTC, pconrad requested changes
One line change requested

2023-06-08 02:05 UTC, pconrad approved these changes
LGTM

2023-06-08 02:05 UTC, merged